### ISSUE TITLE
Didn't find class "javax.naming.directory.InitialDirContext" on path

### ISSUE THREAD

**Issue by secp192k1** [studo-app/katerbase#8]
Hello!

I'm trying to implement MongoDB into my chatting app and I'm getting the error below, my guess is that `+srv` on the URI
The URI looks like this:
`mongodb+srv://<name>:<password>@cluster0.mwhvy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`

If I remove the `+srv` the app just freezes with no output

Also I'm gonna show how I implemented the lib with a picture of the files tree

Thanks!

---

Tree:
![image](https://user-images.githubusercontent.com/24621566/155046399-fe7d9300-f4f9-43bb-b3b5-c7f89ef3451f.png)

Error:
```console
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.slimakoi.chatroom.v2, PID: 13829
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/naming/directory/InitialDirContext;
        at com.mongodb.internal.dns.DefaultDnsResolver.createDnsDirContext(DefaultDnsResolver.java:151)
        at com.mongodb.internal.dns.DefaultDnsResolver.resolveAdditionalQueryParametersFromTxtRecords(DefaultDnsResolver.java:112)
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:381)
        at com.slimakoi.chatroom.v2.katerbase.MongoDatabase.<init>(MongoDatabase.kt:82)
        at com.slimakoi.chatroom.v2.katerbase.MongoDatabase.<init>(MongoDatabase.kt:40)
        at com.slimakoi.chatroom.v2.MainActivity.onCreate(MainActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.naming.directory.InitialDirContext" on path: DexPathList[[zip file "/data/app/com.slimakoi.chatroom.v2-gp9_GfCm2k1JoxlRrfZ_ig==/base.apk"],nativeLibraryDirectories=[/data/app/com.slimakoi.chatroom.v2-gp9_GfCm2k1JoxlRrfZ_ig==/lib/x86_64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mongodb.internal.dns.DefaultDnsResolver.createDnsDirContext(DefaultDnsResolver.java:151) 
        at com.mongodb.internal.dns.DefaultDnsResolver.resolveAdditionalQueryParametersFromTxtRecords(DefaultDnsResolver.java:112) 
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:381) 
        at com.slimakoi.chatroom.v2.katerbase.MongoDatabase.<init>(MongoDatabase.kt:82) 
        at com.slimakoi.chatroom.v2.katerbase.MongoDatabase.<init>(MongoDatabase.kt:40) 
        at com.slimakoi.chatroom.v2.MainActivity.onCreate(MainActivity.kt:24) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by vonox7** [comment]
Katerbase doesn't support android. Please run it on a JVM server.
